# Generated by Django 4.2 on 2023-05-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userdetails_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRightsDemo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('StringOne', models.CharField(max_length=100)),
                ('StringTwo', models.CharField(max_length=100)),
            ],
        ),
    ]
